# Judge LLM: Evaluates responses from all agents and selects the best one
import os
from dotenv import load_dotenv

load_dotenv()

_llm = None
_prompt = None
_initialized = False


def _initialize():
    """Initialize the Judge LLM. Called lazily on first use."""
    global _llm, _prompt, _initialized

    if _initialized:
        return True

    try:
        from langchain_core.prompts import ChatPromptTemplate
        from langchain_groq import ChatGroq

        groq_api_key = os.getenv("groq1_api_key")
        if not groq_api_key:
            raise ValueError(
                "groq1_api_key not found in environment variables. "
                "Please set it in .env file."
            )

        _llm = ChatGroq(groq_api_key=groq_api_key, model_name="Llama-3.3-70b-Versatile")

        _prompt = ChatPromptTemplate.from_template(
            """
You are a helpful, unbiased evaluator. A question was asked, and multiple agents provided different answers.

Your task is to carefully evaluate **all the responses** and **select the best one** based on:
- Relevance to the question
- Factual accuracy
- Clarity and completeness

## Question
{question}

## Responses:
{answers}

## Instructions:
- Think step by step.
- Compare the responses logically.
- Pick the best one and explain why.
- Return your final answer in the following format:

Best Response Index: <number>
Justification: <brief explanation>
and also give the answer which is generated by that agent
"""
        )

        _initialized = True
        return True

    except Exception as e:
        raise RuntimeError(f"Failed to initialize Judge LLM: {e}")


def responses5(question, answer):
    """Evaluate all agent responses and select the best one."""
    _initialize()

    final_prompt = _prompt.format(question=question, answers=answer)
    response = _llm.invoke(final_prompt)
    # FIX: extract .content string from the LangChain AIMessage object
    if hasattr(response, "content"):
        return response.content
    return str(response)
