from langchain.prompts import ChatPromptTemplate
from langchain_community.llms import Ollama
from langchain_groq import ChatGroq
import os
from dotenv import load_dotenv

load_dotenv()

groq_api_key = os.getenv("groq1_api_key" )


llm = ChatGroq(groq_api_key = groq_api_key, model_name = "Llama-3.3-70b-Versatile")

###Chatprompt template
prompt = ChatPromptTemplate.from_template(
    """
You are a helpful, unbiased evaluator. A question was asked, and multiple agents provided different answers.

Your task is to carefully evaluate **all the responses** and **select the best one** based on:
- Relevance to the question
- Factual accuracy
- Clarity and completeness

##question
{question}
## Responses:
{answers}

## Instructions:
- Think step by step.
- Compare the responses logically.
- Pick the best one and explain why.
- Return your final answer in the following format:

Best Response Index: <number>
Justification: <brief explanation>
and also give the answer which is generated by that agent
""" 
)


def responses5(question,answer):
               
    final_prompt = prompt.format(question = question, answers = answer)
    # final_prompt = prompt.format()


    response = llm.invoke(final_prompt)
    return response

